version: '3.1'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./my_module:/mnt/extra-addons/my_module
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: >
      odoo -d odoo -i my_module --stop-after-init

volumes:
  odoo-db-data:
